### ISSUE TITLE
Do not create hibernate session manually, use container managed resources

### ISSUE THREAD

**Issue by AlphaBeth** [joseortiz9/WebLabs_itmo#10]
https://github.com/joseortiz9/WebLabs_itmo/blob/844720c71bf62b38a6bf81fabcfa6aaf60ef33d9/src/main/java/ru/students/lab/dao/PointDao.java#L14-L17

**Comment by joseortiz9** [comment]
now we use the entity factory
https://github.com/joseortiz9/WebLabs_itmo/blob/eebe6d46d55511d6b2d738f27a6be80a204c6837/src/main/java/ru/students/lab/dao/PointDao.java#L12-L20

https://github.com/joseortiz9/WebLabs_itmo/blob/eebe6d46d55511d6b2d738f27a6be80a204c6837/src/main/java/ru/students/lab/util/JpaUtil.java#L7
