### ISSUE TITLE
Do not create hibernate session manually, use container managed resources (reopen #10)

### ISSUE THREAD

**Issue by AlphaBeth** [joseortiz9/WebLabs_itmo#11]

**Comment by joseortiz9** [comment]
Finally we totally corrected and is working!

https://github.com/joseortiz9/WebLabs_itmo/blob/36c36b2f3ad3781464e806bde6323f66ea188a1e/src/main/java/ru/students/lab/dao/PointDao.java#L21-L22

https://github.com/joseortiz9/WebLabs_itmo/blob/36c36b2f3ad3781464e806bde6323f66ea188a1e/src/main/resources/META-INF/persistence.xml#L7-L12
