### ISSUE TITLE
Unaccaptable

### ISSUE THREAD

**Issue by AlphaBeth** [joseortiz9/WebLabs_itmo#3]
Follow MVC model - separate logic and view. Servlets for logic, jsps for view.

https://github.com/joseortiz9/WebLabs_itmo/blob/74a572a3dcfbeafbc684c21fccf04b5d980a3237/src/ru/students/lab/servlets/AreaCheckServlet.java#L49-L126

**Comment by joseortiz9** [comment]
Fixed adding the saved point to the request parameter and redirecting to the view

https://github.com/joseortiz9/WebLabs_itmo/blob/e00b7309b2c048fa6a847d4e20b277c1f7e2ba3c/src/ru/students/lab/servlets/AreaCheckServlet.java#L44-L45
