### ISSUE TITLE
Magic constant repeated twice

### ISSUE THREAD

**Issue by AlphaBeth** [joseortiz9/WebLabs_itmo#4]
https://github.com/joseortiz9/WebLabs_itmo/blob/74a572a3dcfbeafbc684c21fccf04b5d980a3237/src/ru/students/lab/servlets/AreaCheckServlet.java#L36

**Comment by joseortiz9** [comment]
fixed
https://github.com/joseortiz9/WebLabs_itmo/blob/8d3c3c43e441bc859db29ce2107724435b57a139/src/ru/students/lab/servlets/AreaCheckServlet.java#L19
