### ISSUE TITLE
Bounds validation

### ISSUE THREAD

**Issue by AlphaBeth** [joseortiz9/WebLabs_itmo#5]
https://github.com/joseortiz9/WebLabs_itmo/blob/74a572a3dcfbeafbc684c21fccf04b5d980a3237/src/ru/students/lab/servlets/ControllerServlet.java#L21-L23

**Comment by joseortiz9** [comment]
maybe is not the best solution, but the bounds are validated and returning in the catch to the main view saying that should show the error alert

https://github.com/joseortiz9/WebLabs_itmo/blob/e00b7309b2c048fa6a847d4e20b277c1f7e2ba3c/src/ru/students/lab/servlets/ControllerServlet.java#L21

https://github.com/joseortiz9/WebLabs_itmo/blob/e00b7309b2c048fa6a847d4e20b277c1f7e2ba3c/src/ru/students/lab/servlets/ControllerServlet.java#L33-L36
