### ISSUE TITLE
Configure connection pool in your application server

### ISSUE THREAD

**Issue by AlphaBeth** [joseortiz9/WebLabs_itmo#8]
https://github.com/joseortiz9/WebLabs_itmo/blob/844720c71bf62b38a6bf81fabcfa6aaf60ef33d9/src/main/resources/hibernate.cfg.xml#L8-L10

**Comment by joseortiz9** [comment]
https://github.com/joseortiz9/WebLabs_itmo/blob/eebe6d46d55511d6b2d738f27a6be80a204c6837/src/main/resources/persistence.xml#L10-L19
